//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Book
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Book()
    {
        this.Carts = new HashSet<Cart>();
    }

    public string ISBN { get; set; }
    public Nullable<int> TypeId { get; set; }
    public string Title { get; set; }
    public Nullable<int> Price { get; set; }
    public string Description { get; set; }
    public string Author { get; set; }
    public string Publication { get; set; }
    public string Image { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cart> Carts { get; set; }
    public virtual BookType BookType { get; set; }
    public virtual Img Img { get; set; }
}

public partial class BookType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BookType()
    {
        this.Books = new HashSet<Book>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Book> Books { get; set; }
}

public partial class Cart
{
    public int Id { get; set; }
    public string UserId { get; set; }
    public string BookId { get; set; }
    public Nullable<int> Price { get; set; }
    public Nullable<System.DateTime> DatePurchased { get; set; }
    public Nullable<bool> IsInCart { get; set; }

    public virtual Book Book { get; set; }
}

public partial class Img
{
    public int ID { get; set; }
    public string ISBN { get; set; }
    public byte[] Images { get; set; }

    public virtual Book Book { get; set; }
}

public partial class UserDetail
{
    public int ID { get; set; }
    public string GUID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Address { get; set; }
    public int PostalCode { get; set; }
    public string Email { get; set; }
}
